language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install:
  - cpanm --installdeps --notest Carp Data::Throttler CGI::IDS Data::Validate::URI DateTime LWP::Simple XML::LibXML
  - cpanm --notest Carp Data::Throttler CGI::IDS Data::Validate::URI DateTime LWP::Simple XML::LibXML
script:
  - perl -MO=Lint Allow.pm
