language: perl
os:
  - linux
  # - osx

env: AUTOMATED_TESTING=1

perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  # - "5.20"
  # - "5.18"
  # - "5.16"
  # - "5.14"
  # - "5.12"

sudo: false

install:
  - cpanm -iqn Carp Data::Throttler CGI::IDS Data::Validate::URI DateTime LWP::Simple XML::LibXML B::Lint warnings::unused

script:
  - perl -MO=Lint Allow.pm
  - perl -cwT -Mwarnings::unused Allow.pm

jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        - cinst -y strawberryperl
        - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
      # install:
        # - cpanm --notest --installdeps .
      script:
        - perl -MO=Lint Allow.pm
        - perl -cwT -Mwarnings::unused Allow.pm
